name: Docker Image CI

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GHCR_PAT }}
          submodules: true

      - name: Prepare Environment
        uses: nelonoel/branch-name@v1.0.1

      - name: Publish Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: poketwo
          password: ${{ secrets.GHCR_PAT }}
          registry: ghcr.io
          image_name: poketwo
          image_tag: latest,${{ env.BRANCH_NAME }},${{ github.sha }}
